version: '3.3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 'habrparse_db'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  habrpars:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/habrparse_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  pgdata: