version: '3.3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  parseservice:
    build:
      context: ./parseservice
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${HABRPARS_PORT_EXTERNAL}:${HABRPARS_PORT_INTERNAL}"
    depends_on:
      - postgres
      - djangoapp

  djangoapp:
    build:
      context: ./webclient
      dockerfile: Dockerfile
    ports:
      - "${DJANGOAPP_PORT}:8000"
    env_file: .env
    depends_on:
      - postgres

volumes:
  pgdata: