version: '3.3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 'habrparse_db'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  habrpars:
    build:
      context: ./parseservice
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/habrparse_db
      SERVER_ADDR: :8080
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - djangoapp

  djangoapp:
    build:
      context: ./webclient
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - postgres

volumes:
  pgdata: