# Generated by Django 5.0.1 on 2024-01-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(unique=True)),
                ('timeout', models.PositiveIntegerField(default=600)),
            ],
            options={
                'db_table': 'hubs',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('url', models.TextField(unique=True)),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_url', models.TextField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.hub')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
